Added trade processing + refactor
northwesternfintech/raccoon pull request #9
Opened 2023-07-19 22:28 UTC by stevenewald

2023-07-19 22:46 UTC, egelja requested changes
Looks great for the most part. Small changes incoming.

2023-07-19 22:46 UTC, egelja commented on src/storage/orderbook.cpp
> +            if (volume == 0.0) {
```suggestion
            if (volume <= 0.0000000001) {
```
Otherwise GCC gets sad

2023-07-19 22:46 UTC, egelja commented on src/storage/orderbook.cpp
> +    std::vector<std::string> kvPairs;
```suggestion
    std::vector<std::string> kvPairs; // container for strings
```

2023-07-19 22:46 UTC, egelja commented on src/storage/orderbook.hpp
> +    void ob_to_redis_(redisContext* redis, const std::string& product_id);
```suggestion
    void process_incoming_snapshot(const OrderbookSnapshot& newOb);
    void process_incoming_update(const OrderbookUpdate& newUpdate);
    void ob_to_redis(redisContext* redis, const std::string& product_id);
```

Underscore only for private methods

2023-07-19 22:46 UTC, egelja commented on src/storage/processing.hpp
> +    void process_incoming_data_(const std::string& data);
```suggestion
    void process_incoming_data(const std::string& data);
```

2023-07-19 22:46 UTC, egelja commented on src/storage/trades.cpp
> +    redisReply* reply = static_cast<redisReply*>(
```suggestion
    auto* reply = static_cast<redisReply*>(
```

2023-07-19 22:46 UTC, egelja commented on src/storage/trades.hpp
> +    void matches_to_redis_(redisContext* redis);
```suggestion
    void process_incoming_match(const Match& match);
    void matches_to_redis(redisContext* redis);
```

2023-07-19 22:46 UTC, egelja commented on src/storage/trades.cpp
> +    matches_.push_back(match);
Hmm

I feel like there's a smarter way to do this

We could do a [`SET`](https://redis.io/commands/set/) with expiry and then a [`SCAN`](https://redis.io/commands/scan/)

That way we don't even have to maintain the list of matches, and redis creates the rolling window for us.

2023-08-15 16:13 UTC, stevenewald commented on src/storage/trades.cpp
> +    redisReply* reply = static_cast<redisReply*>(
no

2023-08-15 19:20 UTC, egelja commented on src/storage/trades.cpp
> +    redisReply* reply = static_cast<redisReply*>(
ok

2023-08-16 00:20 UTC, egelja commented
@stevenewald FYI you've got a merge conflict

2023-08-17 16:02 UTC, merged